### ISSUE TITLE
How do I Uninstall cm4io-fan from raspberrypi?

### ISSUE THREAD

**Issue by niraj711** [neg2led/cm4io-fan#13]
I installed it fine, but if I want to uninstall it, how would I do that?

**Comment by neggles** [comment]
Hi! Hmm, that depends on how you installed it - if you used the .deb package (which is a bit out of date) then `sudo apt purge cm4io-fan` should do it, in theory at least.

If you installed it manually, this should remove it - <version> will be `0.1.1` or `0.2.0` in these commands:

1. `sudo dkms uninstall cm4io-fan/<version>` 
2. `sudo dkms remove cm4io-fan/<version>`
3. `sudo rm -fr /usr/src/cm4io-fan-<version>`
4. Remove or comment out the line beginning with `dtoverlay=cm4io-fan,` from `/boot/config.txt`
5. Optionally remove or comment out the `dtparam=i2c_vc=on` line in `/boot/config.txt` as well (should be directly above the `dtoverlay=` line)
6. Reboot

If you're not having issues with the DKMS module, you can just remove the line from `/boot/config.txt` to stop the module loading.

If that doesn't work, let me know what version you have installed and how you installed it, and I'll see what I can do. Will also add some uninstall instructions to README.md when I get a chance 😃

**Comment by neggles** [comment]
I'm going to assume that worked for you and close this - feel free to reopen if not :)
