### ISSUE TITLE
headers for kernel 5.15.32-v8+ cannot be found

### ISSUE THREAD

**Issue by rapkin61** [neg2led/cm4io-fan#14]
**sudo dkms install cm4io-fan-0.2.0**

Creating symlink /var/lib/dkms/cm4io-fan/0.2.0/source ->
                 /usr/src/cm4io-fan-0.2.0

DKMS: add completed.
Error! Your kernel headers for kernel 5.15.32-v8+ cannot be found.
Please install the linux-headers-5.15.32-v8+ package,
or use the --kernelsourcedir option to tell DKMS where it's located

Don't know if this really is a problem.
Kernel  5.15.32-v8+ came via apt upgrade, but kernel headers obviously haven't been updated too;

**apt show -a linux-headers-arm64**
Package: linux-headers-arm64
Version: 5.10.113-1
Built-Using: linux (= 5.10.113-1)
Priority: optional
Section: kernel
Source: linux-signed-arm64 (5.10.113+1)
Maintainer: Debian Kernel Team <debian-kernel@lists.debian.org>
Installed-Size: 10,2 kB
Provides: linux-headers-generic
Depends: linux-headers-5.10.0-14-arm64 (= 5.10.113-1)
Homepage: https://www.kernel.org/
Download-Size: 1.180 B
APT-Manual-Installed: no
APT-Sources: http://deb.debian.org/debian-security bullseye-security/updates/main arm64 Packages
Description: Header files for Linux arm64 configuration (meta-package)
 This package depends on the architecture-specific header files for the
 latest Linux kernel arm64 configuration.

Package: linux-headers-arm64
Version: 5.10.106-1
Built-Using: linux (= 5.10.106-1)
Priority: optional
Section: kernel
Source: linux-signed-arm64 (5.10.106+1)
Maintainer: Debian Kernel Team <debian-kernel@lists.debian.org>
Installed-Size: 10,2 kB
Provides: linux-headers-generic
Depends: linux-headers-5.10.0-13-arm64 (= 5.10.106-1)
Homepage: https://www.kernel.org/
Download-Size: 1.180 B
APT-Sources: http://deb.debian.org/debian bullseye/main arm64 Packages
Description: Header files for Linux arm64 configuration (meta-package)
 This package depends on the architecture-specific header files for the
 latest Linux kernel arm64 configuration.

**Comment by rapkin61** [comment]
ah ... got it!

**sudo apt install raspberrypi-kernel-headers** 

did the trick ...

**Comment by neggles** [comment]
Ah, yep! Interesting, installing `dkms` should normally bring those in by default... Glad you got it sorted!

**Comment by rapkin61** [comment]
Hmmm ... maybe it should, but unfortunately it doesn't. I installed dkms this morning, but that did not update the kernel headers.
On the other hand ... installing raspberrypi-kernel-headers triggered the dkms build ...
