### ISSUE TITLE
dkms install problem

### ISSUE THREAD

**Issue by racky1** [neg2led/cm4io-fan#16]
Hi, can you tell me why the install fails with:

Copying source to /usr/src/cm4io-fan-0.2.0...Done
Running DKMS install...
Error! Your kernel headers for kernel 5.15.76-v8+ cannot be found.
Please install the linux-headers-5.15.76-v8+ package,
or use the --kernelsourcedir option to tell DKMS where it's located

**Comment by twoseascharlie** [comment]
Can you confirm you actually have those linux kernel headers?

check these:
```shell
# see what headers you might have:
ls -al1 /usr/src/
ls -al1 /lib/modules

# try and install headers raspberry pi
sudo apt install raspberrypi-kernel-headers

# try and install headers debian:
sudo apt install linux-headers-5.15.76-v8+

# check which headers are available for install for debian:
apt search linux-headers-
```

just an fyi as well, a mainline driver was merged for raspberry pi with raspberrypi/linux/pull/5026

**Comment by racky1** [comment]
> Can you confirm you actually have those linux kernel headers?
> 
> check these:
> 
> ```shell
> # see what headers you might have:
> ls -al1 /usr/src/
> ls -al1 /lib/modules
> 
> # try and install headers raspberry pi
> **sudo apt install raspberrypi-kernel-headers**
> 
> # try and install headers debian:
> sudo apt install linux-headers-5.15.76-v8+
> 
> # check which headers are available for install for debian:
> apt search linux-headers-
> ```
> 
> just an fyi as well, a mainline driver was merged for raspberry pi with [raspberrypi/linux/pull/5026](https://github.com/raspberrypi/linux/pull/5026)

Charlie you are the man!  the 

sudo apt install raspberrrypi-kernel-headers was the issue.

I failed to mention that I'm using a CM4 for this project.

Thanks!!  Have a Merry Christmas and Happy Holidays

**Comment by twoseascharlie** [comment]
thanks, hope you have a good holidays as well! 😃

**Comment by neggles** [comment]
Awesome to see people helping each other out like this 😄 Thanks @twoseascharlie! 

Worth noting that the upstream/mainline driver doesn't make use of any of the nice features these chips have; it doesn't use the closed-loop RPM control at all and runs solely in direct-PWM mode, which is a bit of a waste really... kind of defeats the purpose of using an intelligent fan controller with closed-loop RPM control 🤷

The current driver was written by nVidia, and unfortunately was submitted upstream about a week before Matt from Traverse [submitted an updated version of this one](https://lore.kernel.org/all/20220914053030.8929-1-matt@traverse.com.au/), so nVidia's won out by default. I don't have time to work on patches adding closed-loop control to that upstream driver, but Matt is probably working on something & I'll take another look if I do have time.

Might add a note to README with that info.
