### ISSUE TITLE
Kernel 5.10.46 problem

### ISSUE THREAD

**Issue by bluuu81** [neg2led/cm4io-fan#2]
I can't load module for 5.10.46 kernel, i get : modprobe: ERROR: could not insert 'emc2301': Exec format error
It works on 5.10.17

**Comment by neggles** [comment]
Hi! Sorry for the slow reply, it's been A Week, heh.

Hmm. Not sure what's going on there, might be an issue with DKMS uninstall not working properly. Did you use the .deb or clone the repo directly? I have had some... Issues with the .deb. I don't know that it actually works properly.

If you used the repo directly, try running:
```
sudo dkms uninstall cm4io-fan/0.1.0-2 --all
sudo dkms remove cm4io-fan/0.1.0-2 --all
sudo dkms add cm4io-fan/0.1.0-2
sudo dkms install cm4io-fan/0.1.0-2
```
(swap out `cm4io-fan/0.1.0-2` for whatever you named your /usr/src/ subdir)

If you used the .deb, try purging the .deb and reinstalling. I don't have a 5.10.46 kernel available on my CM4 at the moment, which makes testing a little difficult. Some more detailed logs from the uninstall/reinstall would be helpful :)

**Comment by neggles** [comment]
Closing this due to lack of reply :(
