### ISSUE TITLE
fuse: mount failed: Permission denied #179

### ISSUE THREAD

**Issue by iwtfnsc** [neg2led/cm4io-fan#5]
我想问一下，fuse: mount failed: Permission denied #179
这个问题你是怎么解决的，ＳＳＨＦＳ挂载问题，我看你取消了，应当是解决了吧，我已经好几天了，在搞这个问题

**Comment by neggles** [comment]
Apologies, I'm working with a machine translation here, but I don't believe this is related to the cm4io-fan module - this appears to be an error with SSHFS/FUSE, which are userspace utilities entirely unrelated to this module. It cannot be responsible for errors in FUSE, it doesn't touch anything even remotely related to it.
