### ISSUE TITLE
I2C needs to be enabled - maybe add to README?

### ISSUE THREAD

**Issue by geerlingguy** [neg2led/cm4io-fan#9]
I wanted to note that on a fresh Raspberry Pi OS install, I also had to go in and enable I2C for the driver to work:

```
# Enable I2C bus 1.
dtparam=i2c_vc=on
```

Should this be documented in the README? Or is it actually _not_ necessary? I didn't see the driver load in dmesg if I didn't have this setting enabled in `/boot/config.txt`.

**Comment by sdwilsh** [comment]
My Waveshare CM4-DUAL-ETH-BASE does require that, and they document it on their product wiki that it's required in order to access the chip.  Is this board dependent (although I bet most, if not all, need this)?

**Comment by neggles** [comment]
Sorry I missed this! All my notification settings are messed up, apparently...

Yes, this is very board-dependent - anything which starts with the CM4IO board as a base will probably use the same settings it does, though. IIRC the IO board manual includes a note about which I2C bus the chip is on, but I vaguely recall having some trouble finding out the exact config.txt options needed so I will add a note about this to the README.

I wasn't expecting this driver to be so long-lived, tbh - I thought the Traverse guys would upstream this or the Pi Foundation would've add their own driver to raspberrypi/linux by now...

**Comment by neggles** [comment]
OK, it took me absolutely *ages*, but, fixed in 9795410 😄

**Comment by geerlingguy** [comment]
Haha, as is a theme in all my repos... "better late than never!"
